version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
    commit-message:
      prefix: "chore(ci-deps)"
      include: "scope"
