ci:
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
        args: ["--application-directories", "src"]
        exclude: "examples"
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        exclude: "(?:\
            src/djask/project_template|\
            src/djask/admin/api/views.py|\
            docs/|\
            examples\
          )"
        args:
          - "--ignore-missing-imports"
          - "--implicit-reexport"
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.8.0
    hooks:
      - id: pip-compile
        files: ^docs/requirements\.(in|txt)$
        args:
          - "docs/requirements.in"
          - "--no-emit-index-url"
          - "-o"
          - "docs/requirements.txt"
