#! /bin/bash
# Generate a setup.py file for compatibility with rtd
pdm export -f setuppy -o setup.py
# Add necessary explanation to the head of the file
sed -i '1s/.*/# This file is generated by the pre-commit hook/' setup.py
sed -i '2 i # It is only for rtd autodoc' setup.py
git add setup.py
