[project]
authors = [
  {name = "andyzhou", email = "andyforever0108@outlook.com"},
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Framework :: Flask",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Internet :: WWW/HTTP :: WSGI",
  "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
dependencies = [
  "flask~=2.0",
  "apiflask~=0.10",
  "flask-sqlalchemy~=2.5",
  "flask-wtf~=0.15",
  "wtforms-sqlalchemy~=0.2",
  "flask-login~=0.5",
  "bootstrap-flask~=1.8",
  "flask-compress~=1.10",
]
description = "An enhanced django-like Flask"
dynamic = ["classifiers"]
keywords = ["flask", "apiflask"]
license = {text = "MIT"}
name = "Djask"
readme = "README.md"
requires-python = ">=3.7"
version = "0.1.0"

[project.urls]
documentation = "https://djask.readthedocs.io"
homepage = "https://github.com/z-t-y/djask"
repository = "https://github.com/z-t-y/djask"

[project.optional-dependencies]
[build-system]
build-backend = "pdm.pep517.api"
requires = ["pdm-pep517"]

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black<22,>=21.9b0",
    "pytest~=6.2",
    "pytest-cov~=3.0",
    "sphinx~=4.2"]

[tool.pytest.ini_options]
addopts = "--cov=djask"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
omit = ["*.html"]
source = ["djask"]
