[project]
name = "djask"
version = "0.1.0"
description = ""
authors = [
    {name = "andyzhou", email = "andyforever0108@outlook.com"},
]
dependencies = [
    "flask~=2.0",
    "apiflask~=0.10",
]
requires-python = ">=3.7"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""


[project.optional-dependencies]
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black<22,>=21.9b0",
    "pytest~=6.2",
]
