name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Lint with black
        run: |
          pip install black
          black --check src
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Lint with mypy
        run: |
          pip install mypy
          mypy --install-types
          mypy src/djask
