name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [
            '3.8',
            '3.9',
            '3.10',
        ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: pdm install --dev
      - name: Run pytest
        run: pdm run pytest
      - name: Generate xml coverage
        run: pdm run coverage xml
      - name: Upload coverage to codecov
        if: ${{ matrix.python == 3.10 && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3
