name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, 3.10]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pdm-project/setup-pdm@main
        if: ${{ matrix.os != 'windows-latest' }}
        name: Setup PDM
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
          enable-pep582: true
      - uses: actions/setup-python@v2.3.2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          python-version: ${{ matrix.python }}
      - name: Install PDM
        if: ${{ matrix.os == 'windows-latest' }}
        run: python -m pip install pdm
      - name: Install dependencies
        run: pdm install --dev
      - name: Run pytest
        run: pdm run pytest
      - name: Generate xml coverage
        run: pdm run coverage xml
      - name: Upload coverage to codecov
        if: ${{ matrix.python == 3.9 && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2
