name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [
            '3.8',
            '3.9',
            '3.10',
        ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Initialize venv on unix
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          python3 -m venv venv
          . venv/bin/activate
      - name: Initialize venv on windows
        if: ${{ matrix.os == 'windows.latest' }}
        run: |
          python -m venv venv
          venv\Scripts\activate
      - name: Install deps
        run: |
          pip3 install -e .
          pip3 install -r requirements/dev.txt
      - name: Run pytest
        run: pytest
      - name: Generate xml coverage
        run: coverage xml
      - name: Upload coverage to codecov
        if: ${{ matrix.python == 3.10 && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v2
